### PR TITLE
specifying commands and filename for installing amethyst in README.md

### PR DESCRIPTION
**Pull request by adlerhsieh**
I believe many people are not familiar with crystal `deps` package manager and don't know they can start a amethyst application from scratch, so I make it easier to follow in README.

### CODE REVIEW

**Comment by davidpatters0n** [comment]
@adlerhsieh - having followed the newly updated readme it appears after running `crystal deps` it will throw `Missing shard.yml`. Upon adding the `shards.yml` and executing `crystal deps` nothing appears to have been installed and my libs directory is empty. Given this when I try to execute: `rystal libs/amethyst-examples/test.cr` it gives me the following: 

> Error: unknown command: libs/amethyst-examples/test.cr

**Comment by adlerhsieh** [comment]
@davidpatters0n Thanks for bringing this up. Crystal just released 0.8.0 and uses [shards](https://github.com/ysbaddaden/shards) as its dependencies manager. If you're using 0.8.0 the `crystal deps` won't work. 

However, it seems like `Amethyst` itself has some issues starting its server in 0.8.0. I would suggest you use Crystal 0.7.7 instead if you wanna try `Amethyst` out now. I believe the team is working on it.

**Comment by davidpatters0n** [comment]
@adlerhsieh ah I see thank you for the update. :+1:

**Comment by davidpatters0n** [comment]
@adlerhsieh another thing I noticed is that you added `crystal libs/amethyst-examples/test.cr` shouldn't this be `crystal amethyst-examples/src/test.cr` ?

**Comment by adlerhsieh** [comment]
Yeah, definitely. The `/src` is missing.

**Pull request merged**
